version: '3'

services:
  db:
    image: mariadb:10.9.7
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: couplix
    networks:
      - my-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - my-network
    links:
      - db

networks:
  my-network:
